travis:
  secure:
    BINSTAR_TOKEN: UCmx6pzRd4EtnpvxT0UDqHtsgF0WZGhvHokLpuOu9Tu9IQEnjYXWpKxb5cF+YwTSzxs7NdurN4RP3JyRB9VOSDqZj2jvosr4iOIQ6JNH7k9tmPE91hGYImTDpREpsASqPUbKl2jipm/G/GoQVSL0jIrTlUDbRrMGo26gsbgWpAzRa7Wpz7Wf8ve2+6RFR/+g8bwCafz9Jg0Eg4kfYGdtz2NOrNzo3D/eSQyjkD9RQSdWvP42oPpLeZv/QHy6CwUmQzOVtAE3NpbC/lCJ8J9dZcxtwn50S3pZvwDrnQRb9GnccpHmGQ07Lt772KZjNsERr450M+Re4aqbxUEsv7K8IJxkRIlaUFKe1EVJu/g1eGgkR0oY6HKxQTxWGT9fHkV4bX52tGOYF6upRw7cwwpKh4rrRTqmPFSTclxPyOwx/xCsKclkOCONx2eHBOOY8JOixVtQvj9zKYa/KgmqZiZAWhSO9SB4NbatdjdMtDX/IuTZQhbqmnK2eiOG0VLZ4nJn0ukSMc3dCVLDpGWrIoF/aSaAUx71x80+sS1NUlaOfclZdXG3kv0y8qqrU3M7VXZZVnKOGn8+mWTxeZQD29Lgj0bnNOd+uImBYGx9PWMJdeeOkciLRstHzikpLJl9uirXl92Ay67xRf2nacKXd+whUrm9VZD0bLFO9mIM5LxcEOY=
appveyor:
  secure:
    BINSTAR_TOKEN: 1MlC0l7+/rYF4Y1X2kdp80m8xkxiZ29EpALFncIXvSYFr8/h8bRmmIgmNRzrIIlO
channels:
  targets:
  - [mathieu, main]
