travis:
  secure:
    BINSTAR_TOKEN: uyqyjaB//qoXXJenInZViQpfVqlmzwVanlbcuUD3oysSbGgkV1IbNuhk0eJTjlQcolHtoKEurybdVqPgemBK83/tynE6yx89S0VSJVcqospViC3323lVPfsuA16nwQEjh4CeSLcpwZfax3gKqqKLwBBSqI4lScqeofZO0CS74p6NU6Jg+foiiEG+h9ZPmprFHF6FZToo6e49Xci5U/LLNVF806snByeS6xiIYVz9EGH0yoAkDA+H+mfFUcxeggnlmzzcpO4vIlvqF7MLD2LS23JUfKibCXePDlfaC8bmIaMkF6gfimVD2ue1lWVhowv5TYA8geQMq6bQBHhb5l9WCc0JYR6N9KN2gr3FryN8lUswpZL9EvHcrLE9ZptnfXUa5SsFkpMXpB/5VBfxqwP5AzUeyceZ30Lff4NTxIaMxhtGmBzibJan9+dF8g0FWzu5o/PMrr2/mAW5lDAAUMAA56a+g/ZM+yytyAm/RqpLQeUiD08H+8b5Ij2R2A6z4Ikw0FyxiZVEC8KRoYiGwU7DoxV2zFXwQa3zLV4rHHOS59RBqovix79Yp/dp79sWey6Vnw1Iu3oIDeEBOXBcvkio8UB+pf6DMvGWaezYEMOqrnvSOdlT4iS23/oK1YNk82+cWsabp0sV8C8pjEPx2pJG9x4I5x/9YcVJrOoem9mushk=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
