travis:
  secure:
    BINSTAR_TOKEN: rBX7+AI4UMPtHGLRnawO5YF/gWSFNp0Bc2Cj+aHibq8sC7Yv55QKvSLHWlhSnbFQSEvoT5/dyX2UoGHlF71K+g6Ew6ELG5jVqit2ZHYFMlbbs8QWqHz8yHqcGge6caVBsJIG3Z8/k/4ubV3qO3DWP4NPESF+fIyP3v9P4980u89gd8FslI0jA3bkxIkL+vSn+p6Ts3JvdQKvaTE18HXN8IcsvNMHlSkOdwUJ+Ru2rnVRBcOFRM455lnrDGjill6qT/zb/NboR5M+1SC7leGFYhx7IaFLpekIly79ZWfDuQHfpwULl8FIQtr+KiPt/clziHjzce/fTJaS7td805a9m7FhWWGmpZE2bpUXjEV9Z75YR2yPfoAcF3eTskn9ZKmmM6oWU9bfbzbqR4MP0XoLrfJA30GCVAywTNG5KwagMzH/RypGKTsJOeyNuczhHPAZhmpXJdvbM1dEMJFBkPWF5gZzhfYKEYlFT3W+Q4GGh3ettSdx6IWvK2Szr+3t8OoTZOqn9MqUcnTQu8X8UWaSo5gEpk6PFJYhGmtA+VoBIZxhAcmSfmY8ivQR3pNuDJHi6OTdvE7r8TGP0uWm9J3XIlGqD0cLByv6md3/W5C8MXhlo05+e82kXcJPo8u3cEHUufIJ1/+CU4oY8AGzOFWB0i+xPEYMtujCdB9NGEhk8io=
appveyor:
  secure:
    BINSTAR_TOKEN: 1MlC0l7+/rYF4Y1X2kdp80m8xkxiZ29EpALFncIXvSYFr8/h8bRmmIgmNRzrIIlO
channels:
  targets:
  - [mathieu, main]
